FROM ubuntu:18.04

ENV APPLICATION_UID 1001
ENV APPLICATION_USER application
ENV APPLICATION_GID 1002
ENV APPLICATION_GROUP application
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get clean && apt-get -y update && apt-get install -y \
    locales \
    curl \
    wget \
    curl \
    apt-utils \
    xz-utils \
    libxrender-dev \
    git \
    lsb-release \
    acl \
    vim \
    software-properties-common \
    nginx \
    nmap \
  && locale-gen en_US.UTF-8

RUN apt-get update && apt-get install -y \
    php-bcmath \
    php-bz2 \
    php-cli \
    php-common \
    php-curl \
    php-cgi \
    php-dev \
    php-fpm \
    php-gd \
    php-gmp \
    php-imap \
    php-intl \
    php-json \
    php-ldap \
    php-mbstring \
    php-mysql \
    php-odbc \
    php-opcache \
    php-readline \
    php-soap \
    php-sqlite3 \
    php-xml \
    php-xmlrpc \
    php-xsl \
    php-zip \
    php-xdebug \
    libicu-dev \
    libldb-dev \
    libpng-dev \
    php-imagick \
    php-redis \
    php-apcu \
    php-pear \
    supervisor \
&& apt-get autoclean

RUN ln -fs /usr/share/zoneinfo/Europe/Bucharest /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata

RUN GOREPLACE_VERSION=1.1.2 \
    && wget -O /usr/local/bin/go-replace https://github.com/webdevops/go-replace/releases/download/$GOREPLACE_VERSION/gr-64-linux \
    && chmod +x /usr/local/bin/go-replace

ADD config/nginx/vhost-common.conf /etc/nginx/sites-available/vhost-common.conf
ADD config/nginx/vhost.conf /etc/nginx/sites-enabled/default

ADD config/php/pool.d/dev.conf /etc/php/7.2/fpm/pool.d/www.conf

ADD config/php/php.ini /etc/php/7.2/fpm/conf.d/99-php.ini
ADD config/php/php.ini /etc/php/7.2/cli/conf.d/99-php.ini

ADD config/supervisor/supervisord.conf /etc/supervisord.conf
ADD config/supervisor/services.conf /etc/supervisor/conf.d/nginx-php.conf

RUN go-replace --mode=line --regex \
    -s '^[\s;]*user[\s]*='  -r "user = $APPLICATION_USER" \
    -s '^[\s;]*group[\s]*=' -r "group = $APPLICATION_GROUP" \
    --path=/etc/php/7.2/fpm/pool.d/ \
    --path-pattern='*.conf'

ADD bootstrap.sh /bootstrap.sh
RUN chmod 700 /bootstrap.sh

ENV BOOTSTRAP /bootstrap.sh

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN mkdir -p /run/php && touch /run/php/php-fpm.sock

EXPOSE 80
EXPOSE 8080

WORKDIR /var/www/html

RUN /bootstrap.sh

RUN curl https://getcomposer.org/installer > composer-setup.php \
    && php composer-setup.php \
    && mv composer.phar /usr/local/bin/composer \
    && rm composer-setup.php

RUN composer global require "hirak/prestissimo:^0.3" \
    && pecl install apcu_bc-beta


CMD ["supervisord", "-c", "/etc/supervisord.conf", "--user", "root"]
