easy_admin:
    entities:
      Job:
        class: App\Entity\Job
        form:
          fields:
              - 'category'
              - 'type'
              - 'company'
              - 'logo'
              - 'url'
              - 'position'
              - 'location'
              - 'description'
              - 'howToApply'
              - 'token'
              - 'email'
              - 'expiresAt'
              - 'createdAt'
              - 'updatedAt'
      Category:
        class: App\Entity\Category
      Affiliate:
        class: App\Entity\Affiliate
