###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: jobeet-mailhog
      ports:
        - "8001:8025"

    redis:
      image: redis:alpine
      container_name: jobeet-redis

    mysql:
      image: mysql:5.7
      container_name: jobeet-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=docker
        - MYSQL_DATABASE=jobeet
        - MYSQL_USER=jobeet
        - MYSQL_PASSWORD=jobeet
      ports:
        - "8002:3306"

    webserver:
      image: nginx:alpine
      container_name: jobeet-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: jobeet-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - ~/.composer:/var/www/.composer
        - ~/.gitconfig:/var/www/.gitconfig
        - ~/.ssh:/var/www/.ssh
