version: '3'

services:
  app:
    container_name: jobeet_app
    build: ./docker/app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ~/.ssh:/home/application/.ssh
      - ~/.gitconfig:/home/application/.gitconfig
      - ~/.composer:/home/application/.composer
    links:
      - mysql
      - mailhog
      - rabbitmq
      - redis
    ports:
      - "80:80"
      - "443:443"
      - "9001:9000"
    env_file: ./docker/.env
    networks:
      default:
        aliases:
          - jobeet.localhost
      jobeet-app: ~
    dns:
      - 8.8.8.8
      - 8.8.4.4

  mysql:
    container_name: jobeet_mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - jobeet-data:/var/lib/mysql
    env_file: ./docker/.env

  redis:
    container_name: jobeet_redis
    image: redis
    ports:
      - "6379:6379"
    env_file: ./docker/.env

  rabbitmq:
    container_name: jobeet_rabbitmq
    build: ./docker/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file: ./docker/.env

  mailhog:
    container_name: jobeet_mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    env_file: ./docker/.env

  phpmyadmin:
    container_name: jobeet_pma
    image: phpmyadmin/phpmyadmin
    links:
      - "mysql:db"
    ports:
      - "8080:80"
    env_file: ./docker/.env

volumes:
  jobeet-data:

networks:
  jobeet-app: ~
